SYSTEM_APPLICATION_NAME: 'Project Name'
ADMIN_EMAIL: admincs@yopmail.com
FROM_EMAIL: admincs@yopmail.com
WEBSITE_OWNER: Owner
TELEPHONE: '+61 458 666 123'
ADMIN_PAGE_LIMIT: '10'
FRONT_PAGE_LIMIT: '20'
ADMIN_DATE_FORMAT: 'd F, Y'
ADMIN_DATE_TIME_FORMAT: 'd F, Y H:i A'
FRONT_DATE_FORMAT: 'd F, Y'
FRONT_DATE_TIME_FORMAT: 'd F, Y'
RESET_URL_EXPIRED: '24'
DEVELOPMENT_MODE: '1'
DEFAULT_CURRENCY: USD
CONTACT_US_TEXT: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
GOOGLE_MAP_KEY: AIzrtyrtyrtyOfM
ADDRESS: India
SMTP_ALLOW: '1'
SMTP_EMAIL_HOST: mail.company.com
SMTP_USERNAME: wwwsmtp@companty.com
SMTP_PASSWORD: password
SMTP_PORT: '25'
SMTP_TLS: '1'
MAIN_FAVICON: IHG056xV41d9aV8YUMGmmDvIWSOBm4W8QKKG4ams.jpeg
MAIN_LOGO: L3bCgoMahSqgvOBUij1S90ab4yps5JouR7xmLbMF.jpeg
dar: test1
ergrweg: rwegtt
CONTACT_EMAIL: 'company Email'
FACEBOOK_URL: 'https://www.facebook.com'
TWITTER_URL: 'https://www.twitter.com'
LINKEDIN_URL: 'https://www.linkedin.com'
GOOGLE_URL: 'https://www.google.com'
WEBSITE_MAP_LOCATION: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d193595.1583091352!2d-74.11976373946234!3d40.69766374859258!2m3!1f0retert9c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sin!4v1568615516394!5m2!1sen!2sin'
